/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_SistemaInterno;

/**
 *
 * @author jessi
 */
public class UI_ModalSemRestricao extends javax.swing.JDialog {

    /**
     * Creates new form UI_ModalSemRestricao
     */
    public UI_ModalSemRestricao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        imgHeader = new javax.swing.JLabel();
        txtMensagem = new javax.swing.JLabel();
        btnPreencherBoleto = new javax.swing.JButton();
        imgPreencherBoleto = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        txtTitulo.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        txtTitulo.setText("Situação Cadastral");
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(240, 30, 410, 60);

        btnFechar.setBorderPainted(false);
        btnFechar.setContentAreaFilled(false);
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar);
        btnFechar.setBounds(810, 30, 70, 60);

        imgHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HEADER MODAL.png"))); // NOI18N
        getContentPane().add(imgHeader);
        imgHeader.setBounds(0, -20, 890, 160);

        txtMensagem.setFont(new java.awt.Font("sansserif", 0, 40)); // NOI18N
        txtMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMensagem.setText("Não constam restrições no CPF informado.");
        getContentPane().add(txtMensagem);
        txtMensagem.setBounds(30, 180, 830, 100);

        btnPreencherBoleto.setBorderPainted(false);
        btnPreencherBoleto.setContentAreaFilled(false);
        btnPreencherBoleto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPreencherBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreencherBoletoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreencherBoleto);
        btnPreencherBoleto.setBounds(170, 340, 520, 90);

        imgPreencherBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnPreencherBoleto.png"))); // NOI18N
        getContentPane().add(imgPreencherBoleto);
        imgPreencherBoleto.setBounds(170, 340, 520, 90);

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG BACKGROUND MODAL.png"))); // NOI18N
        getContentPane().add(imgBackground);
        imgBackground.setBounds(0, 0, 890, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
       UI_FinanceiroConsulta volta = new UI_FinanceiroConsulta();
       volta.setVisible(true);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnPreencherBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreencherBoletoActionPerformed
        UI_FinanceiroDadosBoleto preencherBoleto = new UI_FinanceiroDadosBoleto();
        preencherBoleto.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnPreencherBoletoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_ModalSemRestricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_ModalSemRestricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_ModalSemRestricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_ModalSemRestricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UI_ModalSemRestricao dialog = new UI_ModalSemRestricao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPreencherBoleto;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel imgHeader;
    private javax.swing.JLabel imgPreencherBoleto;
    private javax.swing.JLabel txtMensagem;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
